'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT         = path.resolve(__dirname, '..');
const PAGES_DIR    = path.join(ROOT, 'templates', 'pages');
const PARTIALS_DIR = path.join(ROOT, 'templates', 'partials');
const OUT_DIR      = path.join(ROOT, 'public');

const COMMENT = '<!-- Generated by scripts/build-html.js — edit templates/pages/ not this file -->\n';

/** Load version from version.json */
function loadVersion() {
  const versionFile = path.join(ROOT, 'version.json');
  if (!fs.existsSync(versionFile)) {
    throw new Error(`version.json not found: ${versionFile}`);
  }
  const versionData = JSON.parse(fs.readFileSync(versionFile, 'utf8'));
  return versionData.version || '1.0.0';
}

/** Load a partial by name (e.g. "_head") → file contents */
function loadPartial(name) {
  const file = path.join(PARTIALS_DIR, name + '.html');
  if (!fs.existsSync(file)) {
    throw new Error(`Partial not found: ${file}`);
  }
  return fs.readFileSync(file, 'utf8');
}

/** Process a single page template and write to public/ */
function buildPage(pageFile) {
  let src = fs.readFileSync(pageFile, 'utf8');

  // Extract {{TITLE:...}} value before replacing
  const titleMatch = src.match(/\{\{TITLE:([^}]+)\}\}/);
  const title = titleMatch ? titleMatch[1] : '';

  // Remove the {{TITLE:...}} directive line from the page source
  src = src.replace(/\{\{TITLE:[^}]*\}\}\n?/g, '');

  // Load version from version.json
  const version = loadVersion();

  // Replace {{PARTIAL:_name}} tokens (partials may contain {{TITLE}} placeholder)
  src = src.replace(/\{\{PARTIAL:([^}]+)\}\}/g, (_, name) => {
    return loadPartial(name.trim());
  });

  // Replace {{TITLE}} placeholder (injected by _head partial) with actual title
  src = src.replace(/\{\{TITLE\}\}/g, title);

  // Replace {{VERSION}} placeholder with actual version
  src = src.replace(/\{\{VERSION\}\}/g, version);

  // Prepend generator comment
  src = COMMENT + src;

  // Determine output filename: "index.page.html" → "index.html"
  const baseName = path.basename(pageFile).replace(/\.page\.html$/, '.html');
  const outFile  = path.join(OUT_DIR, baseName);

  fs.writeFileSync(outFile, src, 'utf8');
  console.log(`  built: ${baseName}`);
}

// Main
console.log('Building HTML from templates...');

const pageFiles = fs.readdirSync(PAGES_DIR)
  .filter(f => f.endsWith('.page.html'))
  .map(f => path.join(PAGES_DIR, f));

if (pageFiles.length === 0) {
  console.error('No .page.html files found in templates/pages/');
  process.exit(1);
}

pageFiles.forEach(buildPage);
console.log(`Done — ${pageFiles.length} page(s) built.`);
